server:
  port: 20000
spring:
  application:
    name: todo-kakao
#
#  sql:
#    init:
#      mode: always

  output:
    ansi:
      enabled: always
    ## DB ??
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3308/pmh?serverTimezone=Asia/Seoul
    username: root
    password: 1234
    ## jpa create
  jpa:
    hibernate:
      ddl-auto: none
      ## sql ???
    properties:
      hibernate.format_sql: false
    show-sql: true
    open-in-view: false
#    defer-datasource-initialization: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      file-size-threshold: 0
      enabled: true


oauth:
  kakao:
    client-id: b4540e8cbc457edb51a52d9d49073661
    client-secret: rosgiSEPWbHnenXMuNgM5CDVdDHhTc21

msa:
  jwt:
    secret: abcdefghijklmnopqrstuvwxyz01234567890
