#server:
#  port: 8081

spring:
  application:
    name: ex10
  # SQL 구문 실행
#  sql:
#    init:
#      mode: always

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://maria_container:3306/pmh
    url: jdbc:mariadb://localhost:3308/pmh
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true
    show-sql: true
    open-in-view: false
    # 스프링부트 시작 시 data.sql 자동실행
#    defer-datasource-initialization: true

  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
      file-size-threshold: 0
my:
  value: "welcome to my value"